### ISSUE TITLE
v1. 7 Still Uses Old Gamepad Mappings

### ISSUE THREAD

**Issue by GumbyXGames** [Mike-Aniki/Aniki-ReMake#14]
v1.7 is still using Playnite's default gamepad mappings instead of the new ones mentioned in the changelog. For example, the **X** button brings up launch options insteas of changing view.

_Inverted X/A main view button binding_ and _Swap confirmation/cancelation button bindings_ are disabled in Playnite Input settings.

**Comment by Mike-Aniki** [comment]
It should work, but a bug causes that when you minimize playnite or launch a game, it reverts to the default playnite mapping, the ThemeOption creator is already working on a fix. And I'm also working on a fix for some bugs in the 1.7 themes. 

I'll have to take a look at the inverted X/A, which I hadn't noticed.

Thank you for being reactive and reporting the problems encountered quickly ;) I'll keep you posted on the progress of resolving the problem.

**Comment by Mike-Aniki** [comment]
ThemeOptions v0.23 has just been released, with this version it should fix the problems with the new gamepad mapping, I have also released a theme update "1.7.1" to fix some bugs.

**Comment by ElOso03** [comment]
The text in the theme says “X” to open game details but instead it’s opening the vertical mode of the theme. Is this apart of the same issue? I’ve made sure both the theme and theme options are on the most recent update  but seems it’s not working correctly

**Comment by ElOso03** [comment]
Ah I see what it is, my X/A was inverted within the input menu - thanks for the clarity!

**Comment by GumbyXGames** [comment]
This needs to be reopened. The issue came back with the latest update.
