### ISSUE TITLE
1.8.5 background rendering

### ISSUE THREAD

**Issue by sozasax** [Mike-Aniki/Aniki-ReMake#32]
I love the optimizations made to this version, but I'm having an issue where the background will turn into a gray screen after cycling through the top and bottom bars in the main view. There doesn't seem to be any way to get it back to normal except to disable the bottom bar animation and restart Playnite. Everything seems to work as intended in performance mode.

https://github.com/user-attachments/assets/20f12935-b807-420d-bb9f-26c69f1760ed

The prompt text on the login screen also looks to me misaligned and/or missing text.

![Image](https://github.com/user-attachments/assets/85597b25-fb54-428c-9bfb-12d042ae40ee)

Thank you for the continued work on this theme! It's been my favorite for a while now.

**Comment by Mike-Aniki** [comment]
Thanks a lot for the feedback, really appreciated!

I’ll look into both issues and provide an update soon. The background bug and the login screen misalignment shouldn’t be too hard to fix. I’ll keep you posted once it’s sorted.

Thanks again for your support, glad to hear the theme’s still your favorite !

**Comment by Mike-Aniki** [comment]
Fixed in v1.8.6 : https://github.com/Mike-Aniki/Aniki-ReMake/releases/download/v1.8.6/Aniki_ReMake_bb8728bd-ac83-4324-88b1-ee5c586527d1_1_8_6.pthm

**Comment by sozasax** [comment]
Got it, thank you for the description edits! The text issue is for sure fixed! I saw you write that you'd look into the other issue later, so the rest of this reply would just be for reference:

The gentle zoom effect still happens on 1.8.7 even if Dynamic Zoom is off. The only settings change that _almost_ gives me what I'm looking for is turning the bottom bar animation off entirely. Ideally, I would avoid seeing both the zoom and transparency fade after turning off "Dynamic zoom" and turning on "bottom bar animation." I believe I got the version number incorrect in my last comment when talking about the previous version I saw do this (should be 1.8.1 instead).

I much prefer the less resource intensive version of this theme, and it's not an extremely significant issue to me, so I can just edit my backgrounds on 1.8.7 with the bottom bar animation off in the meantime.
